services:
  otel-collector-service:
    image: local/otel-collector-service:latest
    container_name: otel-collector-service
    hostname: docker-local
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "55678:55678"
      - "55679:55679"
    networks:
      - develop-bridge-network

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true